# Generated by Django 4.0.4 on 2022-06-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0002_articles_comments_delete_course_delete_homework_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_by',
        ),
    ]
